###############################################################################
# ASR API - FastAPI Transcription Service
#
# Spins up only the ASR API service on ${ASR_PORT:-8001}, exposing models
# from ../models into the container.
#
# Best used together with the demo-client that transcribes files in the
# test dataset
#
###############################################################################

services:
  asr-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: asr-api
    container_name: asr_api
    ports:
      - "${ASR_PORT:-8001}:8001"
    volumes:
      - ../models:/models
    restart: unless-stopped
    networks:
      - asr

networks:
  asr:
    driver: bridge
