services:
  asr_api:
    build:
      context: .
      dockerfile: Dockerfile
    image: asr_api
    container_name: asr_api
    ports:
      - "8001:8001"
    volumes:
      - ../models:/app/models
    restart: unless-stopped
    networks:
      - asr

networks:
  asr:
    driver: bridge
